### ISSUE TITLE
Don't empty the generated files during generation

### ISSUE THREAD

**Issue by mxstbr** [StellateHQ/fuse#70]
When making a change to a client fragment, all the typings disappear until the codegen has finished. You can see this in the demo video when I change the client fragment because all the fragment typings get red underlines:

https://github.com/StellateHQ/fuse.js/assets/7525670/b83a867f-b1b4-4082-b450-a5a38b8bacd7

Ideally, they wouldn't disappear while the codegen is running to make for a neater experience in-editor.

**Comment by JoviDeCroock** [comment]
This isn't because the folder gets emptied the reason behind this is how the `graphql()` helper is typed. Every string literal in the first argument is associated with the output value in the generated types, this means that as soon as we start typing we have no match left, an example [here](https://github.com/StellateHQ/fuse.js/blob/main/examples/spacex/fuse/gql.ts#L16).

I think fixing this would be more a task for [`gql.tada`](https://github.com/0no-co/gql.tada) as we only need upfront code generation for that, generating types for a given introspection. After that we will just automatically infer types for any changed selection-set. I think that would be a good future iteration.
